# Balanced Security Policy
# Good default policy for general use cases with reasonable security and usability

name: "balanced"
version: "1.0.0"
level: "balanced"
scope: "global"
description: "Balanced security policy for general use with reasonable restrictions"

# Execution sandbox configuration
execution:
  enabled: true
  sandbox_type: "docker"
  max_memory_mb: 1024
  max_cpu_percent: 80
  timeout_seconds: 300
  network_enabled: false
  allowed_languages:
    - "python"
    - "javascript"
    - "bash"
  denied_imports:
    - "os"
    - "subprocess"
    - "sys"
  resource_monitoring: true

# Filesystem access policy
filesystem:
  restrict_to_repo: true
  temp_dir_access: true
  system_access: false
  max_file_size: 26214400  # 25MB
  max_files_created: 500
  allowed_extensions:
    - ".py"
    - ".js"
    - ".json"
    - ".yaml"
    - ".yml"
    - ".txt"
    - ".md"
    - ".csv"
  denied_extensions:
    - ".exe"
    - ".dll"
    - ".so"
    - ".bat"
  audit_enabled: true

# Network access policy
network:
  default_deny: true
  allowed_domains:
    - "api.github.com"
    - "api.gitlab.com"
    - "httpbin.org"
  denied_domains:
    - "*.malicious.com"
    - "*.evil.org"
  allowed_ports:
    - 80
    - 443
    - 8080
  denied_ports:
    - 22   # SSH
    - 23   # Telnet
    - 25   # SMTP
    - 53   # DNS
  request_timeout: 30
  max_response_size: 10485760  # 10MB
  verify_ssl: true
  rate_limit: 60
  audit_enabled: true

# Policy enforcement settings
enforce_all: true
fail_open: false
audit_enabled: true
violation_threshold: 10

# Policy metadata
tags:
  - "balanced"
  - "default"
  - "general-use"

# Custom injection patterns (in addition to defaults)
injection_patterns:
  - name: "company_data_extraction"
    pattern: "(company|internal|proprietary)\\s+(data|information|secrets?)"
    injection_type: "credential_extraction"
    threat_level: "high"
    description: "Attempts to extract company data"
    action: "block"
    
  - name: "development_bypass"
    pattern: "(development|debug|test)\\s+(mode|access|bypass)"
    injection_type: "jailbreak_attempt"
    threat_level: "medium"
    description: "Attempts to activate development bypass"
    action: "flag"